### ISSUE TITLE
Falla al crear grupo sin nombre

### ISSUE THREAD

**Issue by HugoLG** [ZyanyaVE/Moviles#4]
Si al momento de crear grupo no se introduce un nombre y se intenta crear un grupo la aplicación truena. Hay  que poner una validación de que se haya introducido un nombre.

**Comment by ZyanyaVE** [comment]
Si existe una validación

**Comment by ZyanyaVE** [comment]
My bad, si existía validación, pero la creación de intents y cambio de pantalla se intentaban hacer después del 'if' en vez de dentro
